<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>12d3963f-fe17-41d2-9878-1b9fbf0eea11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div[3]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5988cbcd-2c3e-4567-ab1e-d51bc83a9637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>subject icon</value>
      <webElementGuid>0d11a9a5-1ecc-4392-a114-e588d384e12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1500cb24-0c1b-478c-8cb2-226567dafe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>153d04a0-f41f-4fcf-b37a-c4765d7be77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c17dd7c7-0e52-47f3-b0f0-7c15a7645040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>dfc30b04-e31c-455f-8306-4011915ae45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>612485c1-2993-4679-8b40-c06c9d7b9e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/30.svg</value>
      <webElementGuid>d533ee0c-0351-4f85-9b3e-7a4977ad1dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;MuiBox-root mui-style-jt5o7r&quot;]/div[@class=&quot;MuiBox-root mui-style-1tcs5jj&quot;]/div[@class=&quot;MuiBox-root mui-style-teuld&quot;]/div[@class=&quot;MuiBox-root mui-style-1xhj18k&quot;]/div[@class=&quot;MuiBox-root mui-style-znv2mq&quot;]/img[1]</value>
      <webElementGuid>0f1855c7-8aa4-4f14-aa2a-668a1e37601f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div[3]/div/div/div/div/img</value>
      <webElementGuid>fa1aff47-7343-4df3-b8f7-a9d38026b5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='subject icon'])[3]</value>
      <webElementGuid>6bb937a7-835d-4f3d-bda8-c29e772c1b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/img</value>
      <webElementGuid>f841b40d-0543-47de-8e86-3e1d389d244c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'subject icon' and @src = '/assets/images/icons/30.svg']</value>
      <webElementGuid>9897807a-894a-4112-aec8-b2db7af1d35a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
