<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Reminder</name>
   <tag></tag>
   <elementGuidId>d03d1baf-7f25-4d4f-8f7c-769b134a857c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-body1.mui-style-ijn7xq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/main/div/div[3]/div/div/div/div/div/div[3]/a/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6fc8742d-6da3-4319-a577-4e7b5abd9c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 mui-style-ijn7xq</value>
      <webElementGuid>542a649c-4bf1-4034-901e-1bedcc541943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reminder</value>
      <webElementGuid>cf364408-6323-4de1-959d-94665c2bdd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root mui-style-4qr3bj&quot;]/main[@class=&quot;MuiBox-root mui-style-1o3zpnq&quot;]/div[@class=&quot;MuiBox-root mui-style-yzfxkv&quot;]/div[@class=&quot;MuiBox-root mui-style-1xhj18k&quot;]/div[@class=&quot;MuiBox-root mui-style-6yc624&quot;]/div[@class=&quot;MuiBox-root mui-style-d1gelk&quot;]/div[@class=&quot;MuiBox-root mui-style-ti6v05&quot;]/div[@class=&quot;MuiBox-root mui-style-144eety&quot;]/div[@class=&quot;MuiBox-root mui-style-dgse2j&quot;]/div[@class=&quot;MuiBox-root mui-style-upcxle&quot;]/a[1]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium mui-style-18mwkx2&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 mui-style-ijn7xq&quot;]</value>
      <webElementGuid>735fb7f1-384e-452e-a350-e45547576b84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div[3]/div/div/div/div/div/div[3]/a/button/p</value>
      <webElementGuid>c58679c4-65ac-46ba-ad8b-c0ba25e5a3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::p[36]</value>
      <webElementGuid>9e4f3a71-94fb-4da2-a5dc-bcfc65e53e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tests'])[1]/following::p[36]</value>
      <webElementGuid>4f29a2c1-a1b8-4e95-97ef-d2203915e4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reminder']/parent::*</value>
      <webElementGuid>1d513c1f-aa33-4049-b2ba-f65ceb78c6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/button/p</value>
      <webElementGuid>7940a9d1-9453-4f66-89ab-4f37c1e97333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Reminder' or . = 'Reminder')]</value>
      <webElementGuid>39e72bf8-3bc3-4a11-ab81-b76a0b7a8295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
