<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Back_MuiBox-root mui-style-1f4e7rj_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>7bf8a6e2-66aa-47cc-ad3d-81e375aab6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div/div[8]/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f88474b8-b746-4644-9665-5988f717f468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root mui-style-1f4e7rj</value>
      <webElementGuid>ab28117a-c5ef-43d8-8f06-4ab4bc62c2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/space.svg</value>
      <webElementGuid>32173c30-0057-481f-8db0-2dffd92f7779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>topic image</value>
      <webElementGuid>4b83cd1d-5eab-4b3a-a74f-e09391ee2d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;MuiBox-root mui-style-s8mne9&quot;]/div[@class=&quot;MuiBox-root mui-style-1lu2w1e&quot;]/div[@class=&quot;MuiBox-root mui-style-1u9r2as&quot;]/div[@class=&quot;MuiBox-root mui-style-180cis9&quot;]/div[@class=&quot;MuiBox-root mui-style-35p3gl&quot;]/a[1]/div[@class=&quot;MuiBox-root mui-style-gg4vpm&quot;]/div[@class=&quot;MuiBox-root mui-style-1w1vbxm&quot;]/img[@class=&quot;MuiBox-root mui-style-1f4e7rj&quot;]</value>
      <webElementGuid>6f6e03b1-42e6-43d7-a647-ad1028d65ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[8]/a/div/div/img</value>
      <webElementGuid>536c7ea2-5da9-4355-a4a3-6bbec87f2e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='topic image'])[8]</value>
      <webElementGuid>60fa52c6-ccfb-41b2-8ab3-5b03e0a53b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/div/div/img</value>
      <webElementGuid>7a36723a-c406-4006-8227-1df77ed00bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/space.svg' and @alt = 'topic image']</value>
      <webElementGuid>4bc490a9-75db-4d92-b5db-9a0eb769ee15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
