<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Month</name>
   <tag></tag>
   <elementGuidId>c18440f4-bdad-42c3-95e5-8178317e9b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d4f8566-85b9-4f97-9db1-2470f740bd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary mui-style-8yecqf</value>
      <webElementGuid>3642e42b-e523-4078-bfbd-bdcae77df706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>53be27c7-1e1b-4da5-9b45-9883fc60203c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6c7fcda-180c-42ca-aedc-c299f210a86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>34dac06a-47a4-42d4-af0d-3ea4cbd65d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d861b0f-d840-4ccc-a1d0-549b68f037de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>84a9e8a0-4f4e-4f09-be2d-fb4591bd7d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d3ea1ac-52d6-4522-808c-1ffb8952ec1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>49372ff9-c989-4460-b5de-86cbce401d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root mui-style-4qr3bj&quot;]/main[@class=&quot;MuiBox-root mui-style-1o3zpnq&quot;]/div[@class=&quot;MuiBox-root mui-style-1pk2c09&quot;]/div[@class=&quot;MuiBox-root mui-style-oiir3t&quot;]/div[@class=&quot;MuiBox-root mui-style-17byl02&quot;]/div[@class=&quot;MuiTabs-root mui-style-3ecyts&quot;]/div[@class=&quot;MuiTabs-scroller MuiTabs-fixed mui-style-1anid1y&quot;]/div[@class=&quot;MuiTabs-flexContainer mui-style-k008qs&quot;]/button[@id=&quot;0&quot;]</value>
      <webElementGuid>cc6876d2-0cb3-4635-ba00-09874bec130a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='0']</value>
      <webElementGuid>399b48e4-01b5-40b4-bfaa-ed0e6192c07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div[3]/div/div/div/div/button</value>
      <webElementGuid>6e19469e-46e5-4ba3-8fe9-2aef2fc1d01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate of Improvement'])[1]/following::button[1]</value>
      <webElementGuid>7152586d-4bc1-42b0-a9ad-72ef520767c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::button[1]</value>
      <webElementGuid>d9495ed0-51b4-429e-ad68-d74fb7e4342b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Week'])[1]/preceding::button[1]</value>
      <webElementGuid>ba109621-9864-40ed-a6cb-61e73313a118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::button[2]</value>
      <webElementGuid>a9ea2924-d0b8-414b-b9ea-5262dfeba22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Month']/parent::*</value>
      <webElementGuid>029bde6c-b983-4a16-99fc-4bdec0853b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button</value>
      <webElementGuid>7968d431-4091-46b3-852b-3febbba15fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '0' and (text() = 'Month' or . = 'Month')]</value>
      <webElementGuid>ce7e66b2-2dd3-4cdc-b5bd-2e160aee1775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
