<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4.1 Energy4  74.2 Electricity0  124.3 P_b1a41e</name>
   <tag></tag>
   <elementGuidId>bb242729-8ec4-4c85-923d-87df6d48bc86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ebbc2da0-1a53-4c48-bfba-e9071d633ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root mui-style-afhy9b</value>
      <webElementGuid>9c4d7d04-9258-41da-a2bc-4372125b820d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>2b63cba4-6db5-402a-ac0e-991995569410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4.1 Energy4 / 74.2 Electricity0 / 124.3 Particle model of matter0 / 84.4 Atomic Structure0 / 124.5 Forces2 / 244.6 Waves0 / 134.7 Magnetism and electromagnetism0 / 104.8 Space physics0 / 44.9 Key Ideas0 / 1</value>
      <webElementGuid>d046b3a6-b887-4e4e-8500-762983f70141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)</value>
      <webElementGuid>3cbb6088-1658-4a59-a32d-2fde12c9dbfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='container']</value>
      <webElementGuid>97770d6d-604e-4fef-ba89-cd4f7968ba57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>f7fcaa23-b0e3-4141-97c7-8ddd518c3c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[29]</value>
      <webElementGuid>e12b28d4-1fcb-4879-8a63-89e3a9cbef8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tests'])[1]/following::div[32]</value>
      <webElementGuid>aa1a9e4c-f0dc-4b69-9d7b-cd0e6b720c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate of Improvement'])[1]/preceding::div[91]</value>
      <webElementGuid>b3ffef85-3ca8-43c4-bc55-4e34328db75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::div[91]</value>
      <webElementGuid>59cbdc2a-1a3f-4d7b-9a40-b62332d3ed26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>ca6d338d-3506-4fc8-833b-8133d57dd63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container' and (text() = '4.1 Energy4 / 74.2 Electricity0 / 124.3 Particle model of matter0 / 84.4 Atomic Structure0 / 124.5 Forces2 / 244.6 Waves0 / 134.7 Magnetism and electromagnetism0 / 104.8 Space physics0 / 44.9 Key Ideas0 / 1' or . = '4.1 Energy4 / 74.2 Electricity0 / 124.3 Particle model of matter0 / 84.4 Atomic Structure0 / 124.5 Forces2 / 244.6 Waves0 / 134.7 Magnetism and electromagnetism0 / 104.8 Space physics0 / 44.9 Key Ideas0 / 1')]</value>
      <webElementGuid>3fd8eda2-2566-4140-a80d-bde2f2d5dcd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
