<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Settings_longAnswer</name>
   <tag></tag>
   <elementGuidId>ca35eb8f-706c-483f-8820-bc3327bb32c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='longAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;longAnswer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64f6503f-e91b-47ff-bbd9-c2df813b3361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input mui-style-1m9pwf3</value>
      <webElementGuid>1d42831f-c441-4d11-abe4-00df863f8c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>longAnswer</value>
      <webElementGuid>d6799c01-192e-492f-9393-e54491021937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f749be94-0928-4738-8e93-50c4b735b98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dbb3f7d7-6cc8-4b4e-add6-6265d8a3ac0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root mui-style-4qr3bj&quot;]/main[@class=&quot;MuiBox-root mui-style-1o3zpnq&quot;]/div[@class=&quot;MuiBox-root mui-style-4zn1mv&quot;]/div[@class=&quot;MuiBox-root mui-style-pduvg1&quot;]/div[@class=&quot;MuiBox-root mui-style-z9klkh&quot;]/fieldset[@class=&quot;MuiFormControl-root mui-style-btnlyo&quot;]/div[@class=&quot;MuiFormGroup-root mui-style-qftoh4&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd mui-style-1edmehp&quot;]/span[@class=&quot;MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary PrivateSwitchBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-root MuiCheckbox-colorPrimary mui-style-1ccnkmx&quot;]/input[@class=&quot;PrivateSwitchBase-input mui-style-1m9pwf3&quot;]</value>
      <webElementGuid>a58fcf54-dff2-428e-81f6-75609cefc0ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='longAnswer']</value>
      <webElementGuid>1a223af6-8241-4168-b63f-65edae516145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/fieldset/div/label[2]/span/input</value>
      <webElementGuid>d18729b1-e288-458b-b3b0-73f5f31f13aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/input</value>
      <webElementGuid>4e54ff89-331e-4ec5-8e1b-b318a04c5f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'longAnswer' and @type = 'checkbox']</value>
      <webElementGuid>8b70affe-1749-4426-9f99-821b9664fb4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
