<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Settings_multipleChoice</name>
   <tag></tag>
   <elementGuidId>cf62de01-f211-4943-b75a-32dd841bead5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;multipleChoice&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='multipleChoice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83b5b35c-1911-47f0-836e-ce3dba1eaa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input mui-style-1m9pwf3</value>
      <webElementGuid>0b1df285-6fa3-4a3e-90c4-60027d444757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>multipleChoice</value>
      <webElementGuid>157e32f9-8439-43c0-bd75-e5d7ebaf91de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>13fe114d-aed1-4bc1-8e54-8e5e362fcd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d571c57-e3c4-494c-956b-d03b97884fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;MuiBox-root mui-style-4qr3bj&quot;]/main[@class=&quot;MuiBox-root mui-style-1o3zpnq&quot;]/div[@class=&quot;MuiBox-root mui-style-4zn1mv&quot;]/div[@class=&quot;MuiBox-root mui-style-pduvg1&quot;]/div[@class=&quot;MuiBox-root mui-style-z9klkh&quot;]/fieldset[@class=&quot;MuiFormControl-root mui-style-btnlyo&quot;]/div[@class=&quot;MuiFormGroup-root Mui-error mui-style-qftoh4&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd Mui-error mui-style-1oa1epp&quot;]/span[@class=&quot;MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary PrivateSwitchBase-root MuiCheckbox-root MuiCheckbox-colorPrimary MuiCheckbox-root MuiCheckbox-colorPrimary mui-style-1ccnkmx&quot;]/input[@class=&quot;PrivateSwitchBase-input mui-style-1m9pwf3&quot;]</value>
      <webElementGuid>0c1cff2e-0a1f-4702-8d6e-478206a32a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='multipleChoice']</value>
      <webElementGuid>76cd1431-70e6-472c-906c-d204178cec85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/fieldset/div/label/span/input</value>
      <webElementGuid>39b45548-1e1d-4beb-b378-44ab76c2c1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ac8b112c-9837-4c16-a7bf-53f5fa40c228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'multipleChoice' and @type = 'checkbox']</value>
      <webElementGuid>ead66f0f-1d58-4a0d-8cda-60902fae10c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
